spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bocra_db
    username: bocra_user
    password: bocra_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  cache:
    type: simple

server:
  port: 8080

app:
  jwt:
    secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7173ef44a2e29e48d42d443f7a
    expiration-ms: 604800000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs